USE SHWETASHOP;
SELECT * FROM PAYMENTS;
SELECT SUM(AMOUNT) AS TOTAL_REVENUE FROM PAYMENTS;
SELECT P.PRODUCT_NAME, SUM(OI.QUANTITY * P.PRICE) AS REVENUE_GENERATED
FROM ORDER_ITEM OI JOIN PRODUCTS P ON OI.PRODUCT_ID=P.PRODUCT_ID
JOIN ORDERS O ON OI.ORDER_ID=O.ORDER_ID
WHERE O.ORDER_STATUS="Delivered"
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE_GENERATED DESC;
-- customers who spend more

