 CREATE DATABASE SHWETASHOP;
USE SHWETASHOP;
CREATE TABLE CUSTOMERS
(
   CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
   CUSTOMER_NAME VARCHAR(100),
   EMAIL VARCHAR(150),
   CITY VARCHAR (50),
   SIGNUP_DATE DATE
);
CREATE TABLE PRODUCTS
(
 PRODUCT_ID INT PRIMARY KEY auto_increment,
 PRODUCT_NAME VARCHAR(50),
 CATEGORY VARCHAR(50),
 PRICE DECIMAL(10,2),
 STOCK INT
 );
 CREATE TABLE ORDERS
 ( ODRER_ID INT PRIMARY KEY AUTO_INCREMENT,
 CUSTOMER_ID INT,
 ORDER_DATE DATE,
 ORDER_STATUS VARCHAR(30),
 FOREIGN KEY (CUSTOMER_ID ) REFERENCES CUSTOMERS(CUSTOMER_ID)
  );
 CREATE TABLE ORDER_ITEM 
 (
 ORDERITEM_ID INT PRIMARY KEY AUTO_INCREMENT,
 ORDER_ID INT,
 PRODUCT_ID INT,
 QUANTITY INT,
 FOREIGN KEY(ODRER_ID) REFERENCES ORDERS(ODRER_ID),
 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
 );
 CREATE TABLE PAYMENTS
 (
 PAYMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
 ODRER_ID INT,
 PAYMENT_MODE VARCHAR(30),
 AMOUNT DECIMAL(10,2),
 PAYMENT_DATE DATE,
 FOREIGN KEY(ODRER_ID) REFERENCES ORDERS(ODRER_ID),
 PAYMENT_STATUS VARCHAR(50)
 );
 